### ISSUE TITLE
Music Man!!

### ISSUE THREAD

**Issue by jenessawhite** [AndrewSLentz/markdown-profile#1]
Hey Andrew how many instruments can you play?
what's your favorite (if you play more than one)?

**Comment by AndrewSLentz** [comment]
I play ukulele and piano proficiently (and voice if you want to count that), but I also dabble with guitar and once upon a time I played violin.
My favorite is probably ukulele because it's portable and was really easy to learn to use and improvise on, although I also love the versatility of piano.
